import sqlite3
import json
import os
import datetime
from pathlib import Path

DB_FILE = "scoring_history.db"

def get_db():
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn


def get_image_count():
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT COUNT(*) FROM images")
    count = c.fetchone()[0]
    conn.close()
    return count

def get_images_paginated(page=1, page_size=50, sort_by="score", order="desc"):
    conn = get_db()
    c = conn.cursor()
    offset = (page - 1) * page_size
    query = f"SELECT * FROM images ORDER BY {sort_by} {order.upper()} LIMIT ? OFFSET ?"
    c.execute(query, (page_size, offset))
    rows = c.fetchall()
    conn.close()
    return rows

def image_exists(file_path):
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT 1 FROM images WHERE file_path = ?", (file_path,))
    exists = c.fetchone() is not None
    conn.close()
    return exists

def init_db():
    conn = get_db()
    c = conn.cursor()
    
    # Jobs table
    c.execute('''CREATE TABLE IF NOT EXISTS jobs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        input_path TEXT,
        status TEXT, -- pending, running, completed, failed
        created_at TIMESTAMP,
        completed_at TIMESTAMP,
        log TEXT
    )''')
    
    # Images table
    c.execute('''CREATE TABLE IF NOT EXISTS images (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        job_id INTEGER,
        file_path TEXT UNIQUE,
        file_name TEXT,
        file_type TEXT,
        score REAL,
        normalized_score REAL,
        keywords TEXT,
        metadata TEXT,
        thumbnail_path TEXT,
        scores_json TEXT, -- Full JSON output from scorer
        created_at TIMESTAMP,
        FOREIGN KEY(job_id) REFERENCES jobs(id)
    )''')
    
    
    # Check for missing columns (Schema Migration)
    c.execute("PRAGMA table_info(images)")
    columns = [row[1] for row in c.fetchall()]
    
    if "file_type" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN file_type TEXT")
    
    if "thumbnail_path" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN thumbnail_path TEXT")
        
    if "scores_json" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN scores_json TEXT")

    if "normalized_score" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN normalized_score REAL")

    if "keywords" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN keywords TEXT")

    if "metadata" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN metadata TEXT")

    # Migration for individual scores
    if "score_spaq" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN score_spaq REAL")
    if "score_ava" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN score_ava REAL")
    if "score_koniq" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN score_koniq REAL")
    if "score_paq2piq" not in columns:
        c.execute("ALTER TABLE images ADD COLUMN score_paq2piq REAL")

    conn.commit()
    conn.close()

def create_job(input_path):
    conn = get_db()
    c = conn.cursor()
    c.execute("INSERT INTO jobs (input_path, status, created_at) VALUES (?, ?, ?)",
              (input_path, "pending", datetime.datetime.now()))
    job_id = c.lastrowid
    conn.commit()
    conn.close()
    return job_id

    return job_id

def update_job_status(job_id, status, log=None):
    conn = get_db()
    c = conn.cursor()
    if status in ["completed", "failed"]:
        c.execute("UPDATE jobs SET status = ?, completed_at = ?, log = ? WHERE id = ?",
                  (status, datetime.datetime.now(), log, job_id))
    else:
        c.execute("UPDATE jobs SET status = ?, log = ? WHERE id = ?",
                  (status, log, job_id))
    conn.commit()
    conn.close()

def get_jobs(limit=50):
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT * FROM jobs ORDER BY created_at DESC LIMIT ?", (limit,))
    rows = c.fetchall()
    conn.close()
    return rows

def get_all_images(sort_by="score", order="desc", limit=100):
    conn = get_db()
    c = conn.cursor()
    query = f"SELECT * FROM images ORDER BY {sort_by} {order.upper()} LIMIT ?"
    c.execute(query, (limit,))
    rows = c.fetchall()
    conn.close()
    return rows

def sync_folder_to_db(folder_path, job_id=None):
    """
    Scans a folder for .json files (generated by scoring) and upserts them to DB.
    """
    conn = get_db()
    c = conn.cursor()
    
    count = 0
    # Find all JSONs that look like scoring results
    # We assume valid scoring results have 'summary' key
    folder = Path(folder_path)
    if not folder.exists():
        return 0

    for json_file in folder.glob("*.json"):
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # Simple validation: checks for 'summary' or 'average_normalized_score'
            if "summary" not in data and "average_normalized_score" not in data:
                continue

            # Handle different versions of JSON structure if needed
            # Assuming current structure based on batch_process_images.py
            
            # Extract score
            score = 0
            if "summary" in data:
                score = data["summary"].get("average_normalized_score", 0)
            elif "average_normalized_score" in data:
                score = data["average_normalized_score"]
                
            # Find original image path
            # The JSON usually contains "image_path" but it might be a WSL path if generated inside WSL?
            # Actually batch_process_images.py runs inside WSL but might save WSL paths.
            # We need to map it back or just trust the JSON filename matching the image?
            # Let's rely on the JSON's stated path if it exists, or infer from filename.
            
            image_path = data.get("image_path", "")
            if not image_path:
                # Infer from JSON name
                # image.jpg -> image.json
                stem = json_file.stem
                # Try to find the image file
                for ext in ['.jpg', '.nef', '.png']:
                    probe = folder / (stem + ext)
                    if probe.exists():
                        image_path = str(probe)
                        break
            
            if not image_path:
                image_path = str(json_file.with_suffix('')) # Fallback
                
            file_name = Path(image_path).name
            
            # Upsert
            c.execute('''INSERT OR REPLACE INTO images 
                         (job_id, file_path, file_name, score, scores_json, created_at)
                         VALUES (?, ?, ?, ?, ?, ?)''',
                      (job_id, str(image_path), file_name, score, json.dumps(data), datetime.datetime.now()))
            
            count += 1
        except Exception as e:
            print(f"Failed to sync {json_file}: {e}")
            
    conn.commit()
    conn.close()
    return count

def upsert_image(job_id, result):
    """
    Upsert a single image result from the streaming output.
    result is a generic dictionary (the JSON output from batch_process_images).
    """
    conn = get_db()
    c = conn.cursor()
    
    # Extract fields
    image_path = result.get("image_path", "")
    file_name = result.get("image_name", Path(image_path).name)
    file_type = Path(image_path).suffix.lower().lstrip('.')
    
    # Handle score location variation (summary vs direct)
    score = 0
    normalized_score = 0
    if "summary" in result:
        score = result["summary"].get("average_normalized_score", 0)
        normalized_score = score
    elif "average_normalized_score" in result:
        score = result["average_normalized_score"]
        normalized_score = score
        
    # Individual Scores
    individual_scores = result.get("individual_scores", {})
    
    def get_ind_score(name):
        # Handle cases where value is dict or float
        val = individual_scores.get(name)
        if isinstance(val, dict):
            return val.get("normalized_score", val.get("score", 0))
        if isinstance(val, (int, float)):
            return val
        return 0

    score_spaq = get_ind_score("spaq")
    score_ava = get_ind_score("ava")
    score_koniq = get_ind_score("koniq")
    score_paq2piq = get_ind_score("paq2piq")
        
    # Keywords & Metadata (if present)
    keywords = result.get("keywords", [])
    if isinstance(keywords, list):
        keywords = ",".join(keywords)
        
    metadata = result.get("metadata", {})
    if isinstance(metadata, dict):
        metadata = json.dumps(metadata)
    
    thumbnail_path = result.get("thumbnail_path")
    
    c.execute('''INSERT OR REPLACE INTO images 
                 (job_id, file_path, file_name, file_type, 
                  score, normalized_score, 
                  score_spaq, score_ava, score_koniq, score_paq2piq,
                  keywords, metadata, scores_json, thumbnail_path, created_at)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''',
              (job_id, image_path, file_name, file_type, 
               score, normalized_score,
               score_spaq, score_ava, score_koniq, score_paq2piq,
               keywords, metadata, json.dumps(result), thumbnail_path, datetime.datetime.now()))
    
    conn.commit()
    conn.close()



def get_image_details(file_path):
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT * FROM images WHERE file_path = ?", (file_path,))
    row = c.fetchone()
    conn.close()
    if row:
        return dict(row)
    return {}

