
    CREATE DATABASE 'D:\Projects\image-scoring\test_refactor.fdb' user 'sysdba' password 'masterkey' DEFAULT CHARACTER SET UTF8;
    
    CREATE TABLE images (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_path VARCHAR(4000) NOT NULL,
        is_processed INTEGER DEFAULT 0,
        tags BLOB SUB_TYPE TEXT,
        verification_date TIMESTAMP,
        last_checked TIMESTAMP
    );
    
    CREATE TABLE file_paths (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        image_id INTEGER,
        path VARCHAR(4000),
        last_seen TIMESTAMP
    );
    
    CREATE TABLE resolved_paths (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        image_id INTEGER NOT NULL,
        windows_path VARCHAR(4000) NOT NULL,
        is_verified INTEGER DEFAULT 0,
        verification_date TIMESTAMP,
        last_checked TIMESTAMP
    );

    INSERT INTO images (file_path) VALUES ('/mnt/d/img1.jpg');
    INSERT INTO file_paths (image_id, path) VALUES (1, '/mnt/d/img1.jpg');
    INSERT INTO resolved_paths (image_id, windows_path, is_verified) VALUES (1, 'D:\img1.jpg', 1);
    
    INSERT INTO images (file_path) VALUES ('/mnt/d/img2.jpg');
    INSERT INTO file_paths (image_id, path) VALUES (2, '/mnt/d/img2.jpg');
    
    INSERT INTO file_paths (image_id, path) VALUES (999, '/orphaned.jpg');
    