import os
import sys
import shutil
import sqlite3 # Not used, we use firebird
import glob
import time
import gc
import pytest
from firebird.driver import connect, driver_config, create_database, DatabaseError

# Ensure modules can be imported
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '.')))
import modules.db as db

FB_DIR = os.path.abspath("Firebird")
FB_DLL = os.path.join(FB_DIR, "fbclient.dll")
ISQL_EXE = os.path.join(FB_DIR, "isql.exe")
GFIX_EXE = os.path.join(FB_DIR, "gfix.exe")

# Align Environment
os.environ["FIREBIRD"] = FB_DIR
if FB_DIR not in os.environ["PATH"]:
    os.environ["PATH"] += ";" + FB_DIR

# Setup Driver Config
if hasattr(driver_config, 'fb_client_library'):
     driver_config.fb_client_library.value = FB_DLL

TEST_DB_NAME = "test_refactor.fdb"
TEST_DB_PATH = os.path.abspath(TEST_DB_NAME)
CONNECTION_STRING = TEST_DB_PATH

def cleanup():
    if os.path.exists(TEST_DB_PATH):
        try:
             # Force close any locks?
             pass 
        except: pass
        
    for f in glob.glob(f"{TEST_DB_PATH}*"):
        try:
            os.remove(f)
        except Exception as e:
            print(f"Cleanup error: {e}")

def create_legacy_db():
    cleanup()
    
    script = f"""
    CREATE DATABASE '{CONNECTION_STRING}' user 'sysdba' password 'masterkey' DEFAULT CHARACTER SET UTF8;
    
    CREATE TABLE images (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_path VARCHAR(4000) NOT NULL,
        is_processed INTEGER DEFAULT 0,
        tags BLOB SUB_TYPE TEXT,
        verification_date TIMESTAMP,
        last_checked TIMESTAMP
    );
    
    CREATE TABLE file_paths (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        image_id INTEGER,
        path VARCHAR(4000),
        last_seen TIMESTAMP
    );
    
    CREATE TABLE resolved_paths (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        image_id INTEGER NOT NULL,
        windows_path VARCHAR(4000) NOT NULL,
        is_verified INTEGER DEFAULT 0,
        verification_date TIMESTAMP,
        last_checked TIMESTAMP
    );

    INSERT INTO images (file_path) VALUES ('/mnt/d/img1.jpg');
    INSERT INTO file_paths (image_id, path) VALUES (1, '/mnt/d/img1.jpg');
    INSERT INTO resolved_paths (image_id, windows_path, is_verified) VALUES (1, 'D:\\img1.jpg', 1);
    
    INSERT INTO images (file_path) VALUES ('/mnt/d/img2.jpg');
    INSERT INTO file_paths (image_id, path) VALUES (2, '/mnt/d/img2.jpg');
    
    INSERT INTO file_paths (image_id, path) VALUES (999, '/orphaned.jpg');
    """
    
    with open("setup_legacy.sql", "w") as f:
        f.write(script)
        
    if not os.path.exists(ISQL_EXE):
        print(f"Error: isql.exe not found at {ISQL_EXE}")
        sys.exit(1)
        
    cmd = f'"{ISQL_EXE}" -q -i setup_legacy.sql'
    if os.system(cmd) != 0:
        print("Failed to create legacy DB")
        sys.exit(1)

    print("Legacy DB Created.")
    time.sleep(1)

def run_verification():
    # 1. Setup Legacy State
    create_legacy_db()
    
    # 2. Point db.py to test DB
    db.DB_PATH = TEST_DB_PATH
    db.DB_FILE = TEST_DB_PATH

    # 3. Run Migration (init_db)
    print("Testing db.get_db() directly...")
    try:
        conn = db.get_db()
        print("db.get_db() returned success!")
        conn.close()
    except Exception as e:
        print(f"db.get_db() failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

    print("Running Migration...")
    try:
        db.init_db()
    except Exception as e:
        print(f"Migration Failed with: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    conn = connect(CONNECTION_STRING, user='sysdba', password='masterkey', charset='UTF8')
    c = conn.cursor()
    
    try:
        # 4. Check RESOLVED_PATHS is gone
        c.execute("SELECT count(*) FROM rdb$relations WHERE rdb$relation_name = 'RESOLVED_PATHS'")
        assert c.fetchone()[0] == 0, "RESOLVED_PATHS table should be dropped"
        print("✓ RESOLVED_PATHS dropped")
        
        # 5. Check FILE_PATHS has new columns
        c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'FILE_PATHS'")
        cols = [r[0].strip().lower() for r in c.fetchall()]
        assert 'path_type' in cols, "path_type missing"
        assert 'is_verified' in cols, "is_verified missing"
        print("✓ FILE_PATHS columns added")
        
        # 6. Verify Data Migration
        c.execute("SELECT count(*) FROM file_paths WHERE path_type='WIN'")
        count_win = c.fetchone()[0]
        assert count_win == 1, f"Expected 1 WIN path, found {count_win}"
        
        c.execute("SELECT count(*) FROM file_paths WHERE path_type='WSL'")
        count_wsl = c.fetchone()[0]
        assert count_wsl == 2, f"Expected 2 WSL paths (img1, img2), found {count_wsl}" 
        # Note: orphan (999) should be deleted by FK cleanup logic if we implemented it right?
        # Our migration logic:
        # 1. Update existing to WSL
        # 2. Add WIN paths
        # 3. Apply FK (deletes orphans)
        
        # Verify Orphan Deleted
        c.execute("SELECT count(*) FROM file_paths WHERE image_id=999")
        assert c.fetchone()[0] == 0, "Orphan file_path should be deleted"
        print("✓ Data migration and cleanup successful")
        
        # 7. Verify FK Constraint
        c.execute("SELECT 1 FROM RDB$RELATION_CONSTRAINTS WHERE RDB$CONSTRAINT_NAME = 'FK_FILE_PATHS_IMAGES'")
        assert c.fetchone() is not None, "FK_FILE_PATHS_IMAGES missing"
        print("✓ FK_FILE_PATHS_IMAGES exists")
        
        # 8. Verify Backup Created
        # Look for file matching pattern
        backups = glob.glob(f"{TEST_DB_PATH}.*.bak")
        assert len(backups) > 0, "Backup file should have been created"
        print(f"✓ Backup verified: {backups[0]}")
        
    except Exception as e:
        print(f"Verification Failed: {e}")
        conn.close()
        sys.exit(1)
        
    conn.close()
    print("ALL VERIFICATION STEPS PASSED")
    cleanup()

if __name__ == "__main__":
    run_verification()
