# ruff: noqa: E701
"""Base Firebird tables used by the legacy database adapter."""

from typing import Any


def initialize_base_schema(
    conn: Any,
    *,
    table_exists: Any,
    column_exists: Any,
    index_exists: Any,
    constraint_exists: Any,
    trigger_exists: Any,
) -> tuple[Any, Any, list[str]]:
    """Create core legacy tables and return connection, cursor, and image columns."""
    _table_exists = table_exists
    _column_exists = column_exists
    _index_exists = index_exists
    _constraint_exists = constraint_exists
    _trigger_exists = trigger_exists
    c = conn.cursor()

    # Jobs table
    if not _table_exists(c, 'JOBS'):
        c.execute('''CREATE TABLE jobs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            input_path VARCHAR(4000),
            phase_id INTEGER,
            job_type VARCHAR(50),
            status VARCHAR(50),
            priority SMALLINT DEFAULT 100,
            retry_count INTEGER DEFAULT 0,
            target_scope VARCHAR(255),
            paused_at TIMESTAMP,
            queue_position INTEGER,
            cancel_requested SMALLINT DEFAULT 0,
            queue_payload BLOB SUB_TYPE TEXT,
            created_at TIMESTAMP,
            enqueued_at TIMESTAMP,
            started_at TIMESTAMP,
            finished_at TIMESTAMP,
            completed_at TIMESTAMP,
            log BLOB SUB_TYPE TEXT,
            current_phase VARCHAR(50),
            next_phase_index INTEGER,
            runner_state VARCHAR(50),
            description BLOB SUB_TYPE TEXT
        )''')
        try: conn.commit()
        except Exception: pass

    # Job phases table (persisted multi-step pipeline plans)
    if not _table_exists(c, 'JOB_PHASES'):
        c.execute('''CREATE TABLE job_phases (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id INTEGER NOT NULL,
            phase_order INTEGER NOT NULL,
            phase_code VARCHAR(50) NOT NULL,
            state VARCHAR(20) NOT NULL,
            started_at TIMESTAMP,
            completed_at TIMESTAMP,
            error_message BLOB SUB_TYPE TEXT
        )''')
        try: conn.commit()
        except Exception: pass

    # Job steps table — sub-phase telemetry (e.g. individual ML model runs within Scoring stage)
    if not _table_exists(c, 'JOB_STEPS'):
        try:
            c.execute('''CREATE TABLE job_steps (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id INTEGER NOT NULL,
                phase_code VARCHAR(50) NOT NULL,
                step_code VARCHAR(50) NOT NULL,
                step_name VARCHAR(100) NOT NULL,
                status VARCHAR(20) DEFAULT \'pending\',
                started_at TIMESTAMP,
                completed_at TIMESTAMP,
                items_total INTEGER DEFAULT 0,
                items_done INTEGER DEFAULT 0,
                throughput_rps DOUBLE PRECISION,
                error_message BLOB SUB_TYPE TEXT
            )''')
            conn.commit()
        except Exception:
            conn.rollback()

    # jobs: scope columns for multi-path runs (additive migration)
    try:
        if not _column_exists(c, 'JOBS', 'SCOPE_TYPE'):
            c.execute("ALTER TABLE jobs ADD scope_type VARCHAR(30)")
            conn.commit()
    except Exception:
        conn.rollback()

    try:
        if not _column_exists(c, 'JOBS', 'SCOPE_PATHS'):
            c.execute("ALTER TABLE jobs ADD scope_paths BLOB SUB_TYPE TEXT")
            conn.commit()
    except Exception:
        conn.rollback()

    try:
        if not _column_exists(c, 'JOBS', 'PAUSED_AT'):
            c.execute("ALTER TABLE jobs ADD paused_at TIMESTAMP")
            conn.commit()
    except Exception:
        conn.rollback()

    # Images table
    if not _table_exists(c, 'IMAGES'):
        c.execute('''CREATE TABLE images (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id INTEGER,
            file_path VARCHAR(4000),
            file_name VARCHAR(255),
            file_type VARCHAR(20),
            score DOUBLE PRECISION,
            keywords BLOB SUB_TYPE TEXT,
            title VARCHAR(500),
            description BLOB SUB_TYPE TEXT,
            metadata BLOB SUB_TYPE TEXT,
            thumbnail_path VARCHAR(4000),
            scores_json BLOB SUB_TYPE TEXT,
            created_at TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass
        c = conn.cursor()

    # Check for missing columns (Schema Migration)
    c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'IMAGES'")
    columns = [row[0].strip().lower() for row in c.fetchall()]

    if "file_type" not in columns:
        try: c.execute("ALTER TABLE images ADD file_type VARCHAR(20)")
        except Exception: pass

    if "thumbnail_path" not in columns:
        try: c.execute("ALTER TABLE images ADD thumbnail_path VARCHAR(4000)")
        except Exception: pass

    if "thumbnail_path_win" not in columns:
        try: c.execute("ALTER TABLE images ADD thumbnail_path_win VARCHAR(4000)")
        except Exception: pass

    if "scores_json" not in columns:
        try: c.execute("ALTER TABLE images ADD scores_json BLOB SUB_TYPE TEXT")
        except Exception: pass

    if "image_embedding" not in columns:
        try: c.execute("ALTER TABLE images ADD image_embedding BLOB SUB_TYPE 0")
        except Exception: pass

    # Stacks table
    if not _table_exists(c, 'STACKS'):
        c.execute('''CREATE TABLE stacks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255),
            best_image_id INTEGER,
            created_at TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass

    # Folders table
    if not _table_exists(c, 'FOLDERS'):
        c.execute('''CREATE TABLE folders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            path VARCHAR(4000),
            parent_id INTEGER,
            is_fully_scored INTEGER DEFAULT 0,
            is_keywords_processed INTEGER DEFAULT 0,
            phase_agg_dirty INTEGER DEFAULT 1,
            phase_agg_updated_at TIMESTAMP,
            phase_agg_json BLOB SUB_TYPE TEXT,
            created_at TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass

    # Check For Folders Columns
    if _table_exists(c, 'FOLDERS'):
        c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'FOLDERS'")
        folder_cols = [row[0].strip().lower() for row in c.fetchall()]

        if "is_fully_scored" not in folder_cols:
             try: c.execute("ALTER TABLE folders ADD is_fully_scored INTEGER DEFAULT 0")
             except Exception: pass

        if "is_keywords_processed" not in folder_cols:
             try: c.execute("ALTER TABLE folders ADD is_keywords_processed INTEGER DEFAULT 0")
             except Exception: pass

        # Phase aggregate cache (phase-aware replacement for legacy booleans)
        if "phase_agg_dirty" not in folder_cols:
             try: c.execute("ALTER TABLE folders ADD phase_agg_dirty INTEGER DEFAULT 1")
             except Exception: pass

        if "phase_agg_updated_at" not in folder_cols:
             try: c.execute("ALTER TABLE folders ADD phase_agg_updated_at TIMESTAMP")
             except Exception: pass

        if "phase_agg_json" not in folder_cols:
             try: c.execute("ALTER TABLE folders ADD phase_agg_json BLOB SUB_TYPE TEXT")
             except Exception: pass

        try: conn.commit()
        except Exception: pass

    if not _table_exists(c, 'CLUSTER_PROGRESS'):
        c.execute('''CREATE TABLE cluster_progress (
            folder_path VARCHAR(512) NOT NULL PRIMARY KEY,
            last_run TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass

    # Culling Sessions table
    if not _table_exists(c, 'CULLING_SESSIONS'):
        c.execute('''CREATE TABLE culling_sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            folder_path VARCHAR(4000),
            mode VARCHAR(50),
            status VARCHAR(50) DEFAULT 'active',
            total_images INTEGER DEFAULT 0,
            total_groups INTEGER DEFAULT 0,
            reviewed_groups INTEGER DEFAULT 0,
            picked_count INTEGER DEFAULT 0,
            rejected_count INTEGER DEFAULT 0,
            created_at TIMESTAMP,
            completed_at TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass

    # Culling Picks table
    if not _table_exists(c, 'CULLING_PICKS'):
        c.execute('''CREATE TABLE culling_picks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id INTEGER,
            image_id INTEGER,
            group_id INTEGER,
            decision VARCHAR(50),
            auto_suggested SMALLINT DEFAULT 0,
            is_best_in_group SMALLINT DEFAULT 0,
            created_at TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass

    # Index for fast lookup
    if not _index_exists(c, 'IDX_CULLING_PICKS_SESSION'):
        try: c.execute("CREATE INDEX idx_culling_picks_session ON culling_picks(session_id)")
        except Exception: pass
    if not _index_exists(c, 'IDX_CULLING_PICKS_IMAGE'):
        try: c.execute("CREATE INDEX idx_culling_picks_image ON culling_picks(image_id)")
        except Exception: pass

    # IMAGE_EXIF — cached EXIF metadata (one row per image)
    if not _table_exists(c, 'IMAGE_EXIF'):
        c.execute('''CREATE TABLE image_exif (
            image_id INTEGER NOT NULL PRIMARY KEY,
            make VARCHAR(100),
            model VARCHAR(200),
            lens_model VARCHAR(255),
            focal_length VARCHAR(50),
            focal_length_35mm SMALLINT,
            date_time_original TIMESTAMP,
            create_date TIMESTAMP,
            exposure_time VARCHAR(30),
            f_number VARCHAR(20),
            iso INTEGER,
            exposure_compensation VARCHAR(20),
            image_width INTEGER,
            image_height INTEGER,
            orientation SMALLINT,
            flash SMALLINT,
            image_unique_id VARCHAR(64),
            shutter_count INTEGER,
            sub_sec_time_original VARCHAR(10),
            gps_latitude DOUBLE PRECISION,
            gps_longitude DOUBLE PRECISION,
            gps_altitude DOUBLE PRECISION,
            gps_position_source VARCHAR(20),
            location_resolved BLOB SUB_TYPE TEXT,
            geocoded_at TIMESTAMP,
            geocode_provider VARCHAR(50),
            extracted_at TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass
        c = conn.cursor()

    if _table_exists(c, 'IMAGE_EXIF') and not _constraint_exists(c, 'FK_IMAGE_EXIF_IMAGES'):
        try:
            c.execute("ALTER TABLE image_exif ADD CONSTRAINT fk_image_exif_images FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE")
            conn.commit()
        except Exception: pass
        c = conn.cursor()

    if _table_exists(c, 'IMAGE_EXIF'):
        for idx in ('IDX_IMAGE_EXIF_DATE', 'IDX_IMAGE_EXIF_MAKE', 'IDX_IMAGE_EXIF_MODEL', 'IDX_IMAGE_EXIF_LENS', 'IDX_IMAGE_EXIF_ISO'):
            col = {'IDX_IMAGE_EXIF_DATE': 'date_time_original', 'IDX_IMAGE_EXIF_MAKE': 'make', 'IDX_IMAGE_EXIF_MODEL': 'model', 'IDX_IMAGE_EXIF_LENS': 'lens_model', 'IDX_IMAGE_EXIF_ISO': 'iso'}[idx]
            if not _index_exists(c, idx):
                try: c.execute(f"CREATE INDEX {idx.lower()} ON image_exif({col})")
                except Exception: pass
        # Migration: iso SMALLINT overflows for high ISO (e.g. 51200). Change to INTEGER.
        try:
            c.execute("ALTER TABLE image_exif ALTER COLUMN iso TYPE INTEGER")
            conn.commit()
        except Exception:
            pass  # Column may already be INTEGER or Firebird < 4
        c = conn.cursor()

    # image_exif: GPS and geocoding (additive)
    for col_sql in (
        "ALTER TABLE image_exif ADD gps_latitude DOUBLE PRECISION",
        "ALTER TABLE image_exif ADD gps_longitude DOUBLE PRECISION",
        "ALTER TABLE image_exif ADD gps_altitude DOUBLE PRECISION",
        "ALTER TABLE image_exif ADD gps_position_source VARCHAR(20)",
        "ALTER TABLE image_exif ADD location_resolved BLOB SUB_TYPE TEXT",
        "ALTER TABLE image_exif ADD geocoded_at TIMESTAMP",
        "ALTER TABLE image_exif ADD geocode_provider VARCHAR(50)",
    ):
        try:
            c.execute(col_sql)
            conn.commit()
        except Exception:
            conn.rollback()
        c = conn.cursor()

    # IMAGE_XMP — cached XMP sidecar metadata (one row per image)
    if not _table_exists(c, 'IMAGE_XMP'):
        c.execute('''CREATE TABLE image_xmp (
            image_id INTEGER NOT NULL PRIMARY KEY,
            rating SMALLINT,
            label VARCHAR(50),
            pick_status SMALLINT,
            burst_uuid VARCHAR(64),
            stack_id VARCHAR(64),
            keywords BLOB SUB_TYPE TEXT,
            title VARCHAR(500),
            description BLOB SUB_TYPE TEXT,
            alt_text VARCHAR(500),
            extended_description BLOB SUB_TYPE TEXT,
            create_date TIMESTAMP,
            modify_date TIMESTAMP,
            extracted_at TIMESTAMP
        )''')
        try: conn.commit()
        except Exception: pass
        c = conn.cursor()

    if _table_exists(c, 'IMAGE_XMP') and not _constraint_exists(c, 'FK_IMAGE_XMP_IMAGES'):
        try:
            c.execute("ALTER TABLE image_xmp ADD CONSTRAINT fk_image_xmp_images FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE")
            conn.commit()
        except Exception: pass
        c = conn.cursor()

    if _table_exists(c, 'IMAGE_XMP'):
        for idx in ('IDX_IMAGE_XMP_BURST', 'IDX_IMAGE_XMP_PICK'):
            col = {'IDX_IMAGE_XMP_BURST': 'burst_uuid', 'IDX_IMAGE_XMP_PICK': 'pick_status'}[idx]
            if not _index_exists(c, idx):
                try: c.execute(f"CREATE INDEX {idx.lower()} ON image_xmp({col})")
                except Exception: pass
        if not _column_exists(c, 'IMAGE_XMP', 'ALT_TEXT'):
            try:
                c.execute("ALTER TABLE image_xmp ADD alt_text VARCHAR(500)")
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()
        if not _column_exists(c, 'IMAGE_XMP', 'EXTENDED_DESCRIPTION'):
            try:
                c.execute("ALTER TABLE image_xmp ADD extended_description BLOB SUB_TYPE TEXT")
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()

    # DELETED_IMAGES — tombstone when an image row is deleted (parity with PostgreSQL)
    if not _table_exists(c, 'DELETED_IMAGES'):
        try:
            c.execute(
                """CREATE TABLE deleted_images (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                original_id INTEGER,
                image_uuid VARCHAR(36),
                image_hash VARCHAR(64),
                file_name VARCHAR(255),
                original_path VARCHAR(4000),
                deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )"""
            )
            conn.commit()
        except Exception:
            conn.rollback()
        c = conn.cursor()
    if _table_exists(c, 'DELETED_IMAGES'):
        if not _index_exists(c, 'IDX_DELETED_IMAGES_ORIGINAL_ID'):
            try:
                c.execute(
                    "CREATE INDEX idx_deleted_images_original_id ON deleted_images(original_id)"
                )
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()
        if not _index_exists(c, 'IDX_DELETED_IMAGES_UUID'):
            try:
                c.execute("CREATE INDEX idx_deleted_images_uuid ON deleted_images(image_uuid)")
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()
        if not _index_exists(c, 'IDX_DELETED_IMAGES_HASH'):
            try:
                c.execute("CREATE INDEX idx_deleted_images_hash ON deleted_images(image_hash)")
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()
        if not _index_exists(c, 'IDX_DELETED_IMAGES_FILE_UUID'):
            try:
                c.execute(
                    "CREATE INDEX idx_deleted_images_file_uuid ON deleted_images(file_name, image_uuid)"
                )
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()
        if _table_exists(c, 'IMAGES') and not _trigger_exists(c, 'TRG_RECORD_DELETED_IMAGE'):
            try:
                # image_hash may be absent on very old IMAGES rows; omit OLD.image_hash so trigger compiles everywhere.
                c.execute(
                    """
                    CREATE TRIGGER trg_record_deleted_image FOR images
                    ACTIVE BEFORE DELETE POSITION 0
                    AS
                    BEGIN
                        INSERT INTO deleted_images (original_id, image_uuid, image_hash, file_name, original_path)
                        VALUES (OLD.id, OLD.image_uuid, NULL, OLD.file_name, OLD.file_path);
                    END
                    """
                )
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()

    try: conn.commit()
    except Exception: pass

    return conn, c, columns
