# ruff: noqa: E701
"""Firebird keyword-normalization schema stage."""

from typing import Any


def run_keyword_phase(
    conn: Any,
    *,
    table_exists: Any,
    get_db: Any,
    backfill_keywords: Any,
    backfill_image_xmp: Any,
    logger: Any,
) -> Any:
    """Create keyword tables, run backfills, and return the active connection."""
    _table_exists = table_exists
    _backfill_keywords = backfill_keywords
    _backfill_image_xmp = backfill_image_xmp

    # --- Phase 2: Keyword Normalization + IMAGE_XMP Backfill ---
    try:
        c = conn.cursor()
        print("[Phase 2] Starting Keyword Normalization + IMAGE_XMP Backfill...")

        # 2.1a: KEYWORDS_DIM table
        if not _table_exists(c, "KEYWORDS_DIM"):
            print("  [2.1a] Creating KEYWORDS_DIM table...")
            try:
                c.execute("""CREATE TABLE keywords_dim (
                    keyword_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    keyword_norm    VARCHAR(200) NOT NULL,
                    keyword_display VARCHAR(200),
                    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )""")
                conn.commit()
                c = conn.cursor()

                c.execute(
                    "CREATE UNIQUE INDEX uq_keywords_dim_norm ON keywords_dim(keyword_norm)"
                )
                conn.commit()
                c = conn.cursor()
            except Exception as e:
                logger.warning("KEYWORDS_DIM table creation: %s", e)
                try:
                    conn.rollback()
                except Exception:
                    pass
                c = conn.cursor()

        # 2.1b: IMAGE_KEYWORDS junction table
        if not _table_exists(c, "IMAGE_KEYWORDS"):
            print("  [2.1b] Creating IMAGE_KEYWORDS table...")
            try:
                c.execute("""CREATE TABLE image_keywords (
                    image_id    INTEGER NOT NULL,
                    keyword_id  INTEGER NOT NULL,
                    source      VARCHAR(128) DEFAULT 'auto',
                    confidence  DOUBLE PRECISION,
                    relevance_weight DOUBLE PRECISION DEFAULT 1 NOT NULL,
                    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (image_id, keyword_id)
                )""")
                conn.commit()
                c = conn.cursor()

                c.execute("""
                    ALTER TABLE image_keywords ADD CONSTRAINT fk_imgkw_image
                    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
                """)
                conn.commit()
                c = conn.cursor()

                c.execute("""
                    ALTER TABLE image_keywords ADD CONSTRAINT fk_imgkw_keyword
                    FOREIGN KEY (keyword_id) REFERENCES keywords_dim(keyword_id) ON DELETE CASCADE
                """)
                conn.commit()
                c = conn.cursor()

                c.execute("CREATE INDEX idx_imgkw_image_id ON image_keywords(image_id)")
                conn.commit()
                c = conn.cursor()

                c.execute(
                    "CREATE INDEX idx_imgkw_keyword_id ON image_keywords(keyword_id)"
                )
                conn.commit()
                c = conn.cursor()
            except Exception as e:
                logger.warning("IMAGE_KEYWORDS table creation: %s", e)
                try:
                    conn.rollback()
                except Exception:
                    pass
                c = conn.cursor()

        if _table_exists(c, "IMAGE_KEYWORDS"):
            try:
                c.execute(
                    "ALTER TABLE image_keywords ALTER COLUMN source TYPE VARCHAR(128)"
                )
                conn.commit()
                c = conn.cursor()
            except Exception as e:
                logger.debug("image_keywords.source widen (may already apply): %s", e)
                try:
                    conn.rollback()
                except Exception:
                    pass
                c = conn.cursor()

        if _table_exists(c, "IMAGE_KEYWORDS"):
            try:
                c.execute(
                    "ALTER TABLE image_keywords ADD relevance_weight DOUBLE PRECISION DEFAULT 1 NOT NULL"
                )
                conn.commit()
                c = conn.cursor()
            except Exception as e:
                logger.debug(
                    "image_keywords.relevance_weight add (may already apply): %s", e
                )
                try:
                    conn.rollback()
                except Exception:
                    pass
                c = conn.cursor()

        # Call backfill after tables are created
        if _table_exists(c, "KEYWORDS_DIM") and _table_exists(c, "IMAGE_KEYWORDS"):
            conn.close()
            _backfill_keywords()
            conn = get_db()
            c = conn.cursor()

        # Call IMAGE_XMP backfill as per 2.6
        if _table_exists(c, "IMAGE_XMP"):
            conn.close()
            _backfill_image_xmp()
            conn = get_db()
            c = conn.cursor()

    except Exception as e:
        logger.error("Phase 2 table creation error: %s", e)
        try:
            conn.rollback()
        except Exception:
            pass

    return conn
