# ruff: noqa: E701
"""Additive Firebird migrations retained for legacy databases."""

from typing import Any


def run_additive_migrations(
    conn: Any,
    cursor: Any,
    image_columns: list[str],
    *,
    table_exists: Any,
    index_exists: Any,
    constraint_exists: Any,
    backup_db: Any,
    get_db: Any,
    logger: Any,
) -> Any:
    """Apply historical additive migrations and return the active connection."""
    _table_exists = table_exists
    _index_exists = index_exists
    _constraint_exists = constraint_exists
    _backup_db = backup_db
    c = cursor
    columns = image_columns

    # Additional migrations (Scores etc)
    if not _index_exists(c, 'IDX_STACK_ID') and "stack_id" in columns:
        try: c.execute("CREATE INDEX idx_stack_id ON images(stack_id)")
        except Exception: pass
    if not _index_exists(c, 'IDX_FOLDER_ID') and "folder_id" in columns:
        try: c.execute("CREATE INDEX idx_folder_id ON images(folder_id)")
        except Exception: pass


    c = conn.cursor()
    logger.debug("_init_db_impl started, checking for backup...")
    try:
        # Check if migration needed (e.g. missing columns or old tables)
        migration_needed = False

        # Check if RESOLVED_PATHS exists
        if _table_exists(c, 'RESOLVED_PATHS'):
             logger.debug("RESOLVED_PATHS exists, migration needed.")
             migration_needed = True
        else:
             logger.debug("RESOLVED_PATHS not found.")

        # Check if FILE_PATHS needs columns
        logger.debug("Checking FILE_PATHS columns...")
        c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'FILE_PATHS'")
        fp_cols = [row[0].strip().lower() for row in c.fetchall()]
        logger.debug("FILE_PATHS columns: %s", fp_cols)

        if "path_type" not in fp_cols or "is_verified" not in fp_cols:
             migration_needed = True

        if migration_needed:
             print("Database migration required. Starting backup...")
             # Close conn to release lock for backup
             conn.close()
             logger.debug("Closed conn for backup.")
             _backup_db()
             # Re-open
             logger.debug("Re-opening DB after backup.")
             conn = get_db()
             c = conn.cursor()

        # --- 1. Refactor FILE_PATHS & Merge RESOLVED_PATHS ---

        # Add columns to FILE_PATHS if missing
        # Re-fetch columns in case we reopened? No, we have fp_cols but we need to check again if we want to be safe or just use logic.
        # But wait, if we closed conn, we need to re-fetch?
        # Yes, if we use fp_cols variable it is fine.

        logger.debug("Starting Schema updates...")
        if not _table_exists(c, "FILE_PATHS"):
            c.execute(
                """CREATE TABLE file_paths (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    image_id INTEGER NOT NULL,
                    path VARCHAR(4000),
                    last_seen TIMESTAMP,
                    path_type VARCHAR(10) DEFAULT 'WSL',
                    is_verified SMALLINT DEFAULT 0,
                    verification_date TIMESTAMP
                )"""
            )
            try:
                conn.commit()
            except Exception:
                conn.rollback()
            c = conn.cursor()

        c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'FILE_PATHS'")
        fp_cols = [row[0].strip().lower() for row in c.fetchall()]

        if "path_type" not in fp_cols:
             print("Migrating FILE_PATHS: Adding path_type...")
             c.execute("ALTER TABLE file_paths ADD path_type VARCHAR(10) DEFAULT 'WSL'")
             conn.commit()
             c = conn.cursor() # Refresh cursor

             print("Migrating FILE_PATHS: Updating path_type default...")
             c.execute("UPDATE file_paths SET path_type = 'WSL'")
             conn.commit()
             c = conn.cursor()

        if "is_verified" not in fp_cols:
             print("Migrating FILE_PATHS: Adding is_verified...")
             c.execute("ALTER TABLE file_paths ADD is_verified SMALLINT DEFAULT 0")
             conn.commit()
             c = conn.cursor()
        if "verification_date" not in fp_cols:
             print("Migrating FILE_PATHS: Adding verification_date...")
             c.execute("ALTER TABLE file_paths ADD verification_date TIMESTAMP")
             conn.commit()
             c = conn.cursor()

        # Migrate RESOLVED_PATHS -> FILE_PATHS
        if _table_exists(c, 'RESOLVED_PATHS'):
             print("Migrating RESOLVED_PATHS -> FILE_PATHS...")
             # Move data
             c.execute("""
                INSERT INTO file_paths (image_id, path, path_type, is_verified, verification_date, last_seen)
                SELECT image_id, windows_path, 'WIN', is_verified, verification_date, last_checked
                FROM resolved_paths
             """)
             # Drop old table
             c.execute("DROP TABLE resolved_paths")

        # --- 2. Enforce Integirty (Foreign Keys) ---

        # FK_FILE_PATHS_IMAGES
        if not _constraint_exists(c, 'FK_FILE_PATHS_IMAGES'):
             print("Applying FK_FILE_PATHS_IMAGES...")
             c.execute("DELETE FROM file_paths WHERE image_id NOT IN (SELECT id FROM images)")
             conn.commit()
             c.execute("ALTER TABLE file_paths ADD CONSTRAINT fk_file_paths_images FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE")

        # FK_IMAGES_FOLDERS
        if not _constraint_exists(c, 'FK_IMAGES_FOLDERS') and _table_exists(c, 'FOLDERS'):
             print("Applying FK_IMAGES_FOLDERS...")
             # Set invalid folder_ids to NULL
             c.execute("UPDATE images SET folder_id = NULL WHERE folder_id NOT IN (SELECT id FROM folders)")
             c.execute("ALTER TABLE images ADD CONSTRAINT fk_images_folders FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE SET NULL")

        # FK_FOLDERS_PARENT
        if not _constraint_exists(c, 'FK_FOLDERS_PARENT') and _table_exists(c, 'FOLDERS'):
             print("Applying FK_FOLDERS_PARENT...")
             c.execute("UPDATE folders SET parent_id = NULL WHERE parent_id NOT IN (SELECT id FROM folders)")
             # Prevent self-reference issues? Parent must exist.
             c.execute("ALTER TABLE folders ADD CONSTRAINT fk_folders_parent FOREIGN KEY (parent_id) REFERENCES folders(id) ON DELETE CASCADE")

        # FK_CULLING_PICKS
        if _table_exists(c, 'CULLING_PICKS'):
             if not _constraint_exists(c, 'FK_CULLING_PICKS_IMAGES'):
                 print("Applying FK_CULLING_PICKS_IMAGES...")
                 c.execute("DELETE FROM culling_picks WHERE image_id NOT IN (SELECT id FROM images)")
                 c.execute("ALTER TABLE culling_picks ADD CONSTRAINT fk_culling_picks_images FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE")

             if not _constraint_exists(c, 'FK_CULLING_PICKS_SESSIONS') and _table_exists(c, 'CULLING_SESSIONS'):
                 print("Applying FK_CULLING_PICKS_SESSIONS...")
                 c.execute("DELETE FROM culling_picks WHERE session_id NOT IN (SELECT id FROM culling_sessions)")
                 c.execute("ALTER TABLE culling_picks ADD CONSTRAINT fk_culling_picks_sessions FOREIGN KEY (session_id) REFERENCES culling_sessions(id) ON DELETE CASCADE")

        # Index on path_type
        if _table_exists(c, 'FILE_PATHS') and not _index_exists(c, 'IDX_FILE_PATHS_IMG_TYPE'):
             c.execute("CREATE INDEX idx_file_paths_img_type ON file_paths(image_id, path_type)")

        # Selection feature: cull_decision, cull_policy_version on IMAGES
        c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'IMAGES'")
        img_cols = [row[0].strip().lower() for row in c.fetchall()]
        if "cull_decision" not in img_cols:
            try:
                c.execute("ALTER TABLE images ADD cull_decision VARCHAR(20)")
                conn.commit()
            except Exception as m:
                logger.debug("Adding cull_decision column: %s", m)
                try:
                    conn.rollback()
                except Exception:
                    pass
        if "cull_policy_version" not in img_cols:
            try:
                c.execute("ALTER TABLE images ADD cull_policy_version VARCHAR(50)")
                conn.commit()
            except Exception as m:
                logger.debug("Adding cull_policy_version column: %s", m)
                try:
                    conn.rollback()
                except Exception:
                    pass
        if "image_uuid" not in img_cols:
            try:
                c.execute("ALTER TABLE images ADD image_uuid VARCHAR(36)")
                conn.commit()
            except Exception as m:
                logger.debug("Adding image_uuid column: %s", m)
                try:
                    conn.rollback()
                except Exception:
                    pass
        c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'IMAGES'")
        img_cols_hv = [row[0].strip().lower() for row in c.fetchall()]
        if "hash_version" not in img_cols_hv:
            try:
                c.execute("ALTER TABLE images ADD hash_version INTEGER DEFAULT 1 NOT NULL")
                conn.commit()
            except Exception as m:
                logger.debug("Adding hash_version column: %s", m)
                try:
                    conn.rollback()
                except Exception:
                    pass
        # Unique index on image_uuid to prevent duplicates (allows multiple NULLs)
        if "image_uuid" in img_cols and not _index_exists(c, 'UQ_IMAGES_IMAGE_UUID'):
            try:
                c.execute("CREATE UNIQUE INDEX uq_images_image_uuid ON images(image_uuid)")
                conn.commit()
            except Exception as e:
                logger.debug("Could not create unique index on image_uuid (may have existing duplicates): %s", e)
                try:
                    conn.rollback()
                except Exception:
                    pass

    except Exception as e:
        logger.error("Migration error: %s", e)
        import traceback
        traceback.print_exc()
        try:
            conn.rollback()
        except Exception:
            pass

    # --- Pipeline Phases Tables ---
    try:
        c = conn.cursor()

        # PIPELINE_PHASES — phase registry
        if not _table_exists(c, 'PIPELINE_PHASES'):
            c.execute('''CREATE TABLE pipeline_phases (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code        VARCHAR(50) NOT NULL,
                name        VARCHAR(100) NOT NULL,
                description BLOB SUB_TYPE TEXT,
                sort_order  INTEGER DEFAULT 0 NOT NULL,
                enabled     SMALLINT DEFAULT 1 NOT NULL,
                optional    SMALLINT DEFAULT 0 NOT NULL,
                default_skip SMALLINT DEFAULT 0 NOT NULL
            )''')
            conn.commit()
            c = conn.cursor()
            # Unique index on code
            if not _index_exists(c, 'UQ_PIPELINE_PHASES_CODE'):
                c.execute("CREATE UNIQUE INDEX uq_pipeline_phases_code ON pipeline_phases(code)")
                conn.commit()
                c = conn.cursor()

        # PIPELINE_PHASES — add optional/default_skip columns if missing
        if _table_exists(c, 'PIPELINE_PHASES'):
            c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'PIPELINE_PHASES'")
            pp_cols = [row[0].strip().lower() for row in c.fetchall()]
            if 'optional' not in pp_cols:
                try:
                    c.execute("ALTER TABLE pipeline_phases ADD optional SMALLINT DEFAULT 0 NOT NULL")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding pipeline_phases.optional: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if 'default_skip' not in pp_cols:
                try:
                    c.execute("ALTER TABLE pipeline_phases ADD default_skip SMALLINT DEFAULT 0 NOT NULL")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding pipeline_phases.default_skip: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()

        # IMAGE_PHASE_STATUS — per-image per-phase tracking
        if not _table_exists(c, 'IMAGE_PHASE_STATUS'):
            c.execute('''CREATE TABLE image_phase_status (
                id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                image_id         INTEGER NOT NULL,
                phase_id         INTEGER NOT NULL,
                status           VARCHAR(20) DEFAULT 'not_started' NOT NULL,
                executor_version VARCHAR(50),
                app_version      VARCHAR(50),
                job_id           INTEGER,
                attempt_count    SMALLINT DEFAULT 0 NOT NULL,
                last_error       BLOB SUB_TYPE TEXT,
                started_at       TIMESTAMP,
                finished_at      TIMESTAMP,
                updated_at       TIMESTAMP,
                skip_reason      BLOB SUB_TYPE TEXT,
                skipped_by       VARCHAR(255)
            )''')
            conn.commit()
            c = conn.cursor()

            # Unique constraint on (image_id, phase_id)
            if not _index_exists(c, 'UQ_IMAGE_PHASE'):
                c.execute("CREATE UNIQUE INDEX uq_image_phase ON image_phase_status(image_id, phase_id)")
                conn.commit()
                c = conn.cursor()

            # Performance indexes
            if not _index_exists(c, 'IDX_IPS_IMAGE_ID'):
                c.execute("CREATE INDEX idx_ips_image_id ON image_phase_status(image_id)")
                conn.commit()
                c = conn.cursor()
            if not _index_exists(c, 'IDX_IPS_PHASE_ID'):
                c.execute("CREATE INDEX idx_ips_phase_id ON image_phase_status(phase_id)")
                conn.commit()
                c = conn.cursor()
            if not _index_exists(c, 'IDX_IPS_STATUS'):
                c.execute("CREATE INDEX idx_ips_status ON image_phase_status(status)")
                conn.commit()
                c = conn.cursor()

        # IMAGE_PHASE_STATUS — add skip metadata columns if missing
        if _table_exists(c, 'IMAGE_PHASE_STATUS'):
            c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'IMAGE_PHASE_STATUS'")
            ips_cols = [row[0].strip().lower() for row in c.fetchall()]
            if 'skip_reason' not in ips_cols:
                try:
                    c.execute("ALTER TABLE image_phase_status ADD skip_reason BLOB SUB_TYPE TEXT")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding image_phase_status.skip_reason: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if 'skipped_by' not in ips_cols:
                try:
                    c.execute("ALTER TABLE image_phase_status ADD skipped_by VARCHAR(255)")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding image_phase_status.skipped_by: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()

        # Foreign keys for IMAGE_PHASE_STATUS (safe add)
        if _table_exists(c, 'IMAGE_PHASE_STATUS'):
            if not _constraint_exists(c, 'FK_IPS_IMAGES'):
                try:
                    c.execute("DELETE FROM image_phase_status WHERE image_id NOT IN (SELECT id FROM images)")
                    conn.commit()
                    c = conn.cursor()
                    c.execute("ALTER TABLE image_phase_status ADD CONSTRAINT fk_ips_images FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE")
                    conn.commit()
                    c = conn.cursor()
                except Exception as fk_err:
                    logger.debug("FK_IPS_IMAGES: %s", fk_err)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()

            if not _constraint_exists(c, 'FK_IPS_PHASES'):
                try:
                    c.execute("ALTER TABLE image_phase_status ADD CONSTRAINT fk_ips_phases FOREIGN KEY (phase_id) REFERENCES pipeline_phases(id)")
                    conn.commit()
                    c = conn.cursor()
                except Exception as fk_err:
                    logger.debug("FK_IPS_PHASES: %s", fk_err)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()

        # JOBS — add phase_id column if missing
        if _table_exists(c, 'JOBS'):
            c.execute("SELECT RDB$FIELD_NAME FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'JOBS'")
            jobs_cols = [row[0].strip().lower() for row in c.fetchall()]
            if "phase_id" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD phase_id INTEGER")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.phase_id: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "job_type" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD job_type VARCHAR(50)")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.job_type: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "current_phase" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD current_phase VARCHAR(50)")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.current_phase: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "next_phase_index" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD next_phase_index INTEGER")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.next_phase_index: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "runner_state" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD runner_state VARCHAR(50)")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.runner_state: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "queue_position" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD queue_position INTEGER")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.queue_position: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "enqueued_at" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD enqueued_at TIMESTAMP")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.enqueued_at: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "started_at" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD started_at TIMESTAMP")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.started_at: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "finished_at" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD finished_at TIMESTAMP")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.finished_at: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "cancel_requested" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD cancel_requested SMALLINT DEFAULT 0")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.cancel_requested: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "queue_payload" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD queue_payload BLOB SUB_TYPE TEXT")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.queue_payload: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "priority" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD priority SMALLINT DEFAULT 100")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.priority: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "retry_count" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD retry_count INTEGER DEFAULT 0")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.retry_count: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "target_scope" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD target_scope VARCHAR(255)")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.target_scope: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "description" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD description BLOB SUB_TYPE TEXT")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.description: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            if "paused_at" not in jobs_cols:
                try:
                    c.execute("ALTER TABLE jobs ADD paused_at TIMESTAMP")
                    conn.commit()
                    c = conn.cursor()
                except Exception as m:
                    logger.debug("Adding jobs.paused_at: %s", m)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()
            # FK for phase_id
            if not _constraint_exists(c, 'FK_JOBS_PHASES'):
                try:
                    c.execute("ALTER TABLE jobs ADD CONSTRAINT fk_jobs_phases FOREIGN KEY (phase_id) REFERENCES pipeline_phases(id)")
                    conn.commit()
                    c = conn.cursor()
                except Exception as fk_err:
                    logger.debug("FK_JOBS_PHASES: %s", fk_err)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()

            # Index on jobs.phase_id
            if not _index_exists(c, 'IDX_JOBS_PHASE_ID'):
                try:
                    c.execute("CREATE INDEX idx_jobs_phase_id ON jobs(phase_id)")
                    conn.commit()
                    c = conn.cursor()
                except Exception: pass
            if not _index_exists(c, 'IDX_JOBS_STATUS'):
                try:
                    c.execute("CREATE INDEX idx_jobs_status ON jobs(status)")
                    conn.commit()
                    c = conn.cursor()
                except Exception: pass
            if not _index_exists(c, 'IDX_JOBS_QUEUE_POSITION'):
                try:
                    c.execute("CREATE INDEX idx_jobs_queue_position ON jobs(queue_position)")
                    conn.commit()
                    c = conn.cursor()
                except Exception: pass
            if not _index_exists(c, 'IDX_JOBS_PRIORITY_STATUS'):
                try:
                    c.execute("CREATE INDEX idx_jobs_priority_status ON jobs(status, priority)")
                    conn.commit()
                    c = conn.cursor()
                except Exception:
                    pass
            if not _index_exists(c, 'IDX_JOBS_PAUSED_AT'):
                try:
                    c.execute("CREATE INDEX idx_jobs_paused_at ON jobs(paused_at)")
                    conn.commit()
                    c = conn.cursor()
                except Exception:
                    pass

        # JOB_PHASES migration / constraints / indexes
        if _table_exists(c, 'JOB_PHASES'):
            if not _constraint_exists(c, 'FK_JOB_PHASES_JOB'):
                try:
                    c.execute("DELETE FROM job_phases WHERE job_id NOT IN (SELECT id FROM jobs)")
                    conn.commit()
                    c = conn.cursor()
                    c.execute("ALTER TABLE job_phases ADD CONSTRAINT fk_job_phases_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE")
                    conn.commit()
                    c = conn.cursor()
                except Exception as fk_err:
                    logger.debug("FK_JOB_PHASES_JOB: %s", fk_err)
                    try: conn.rollback()
                    except Exception: pass
                    c = conn.cursor()

            if not _index_exists(c, 'IDX_JOB_PHASES_JOB_ID'):
                try:
                    c.execute("CREATE INDEX idx_job_phases_job_id ON job_phases(job_id)")
                    conn.commit()
                    c = conn.cursor()
                except Exception:
                    pass

            if not _index_exists(c, 'IDX_JOB_PHASES_ORDER'):
                try:
                    c.execute("CREATE INDEX idx_job_phases_order ON job_phases(job_id, phase_order)")
                    conn.commit()
                    c = conn.cursor()
                except Exception:
                    pass

        conn.commit()
    except Exception as e:
        logger.error("Pipeline phases migration error: %s", e)
        try: conn.rollback()
        except Exception: pass

    return conn
