#!/usr/bin/env python3
"""
Migration script for resolved_paths table.

Creates the resolved_paths table and backfills Windows paths for all existing images.
This enables the Windows native ImageGalleryViewer to access files reliably.

Usage:
    python scripts/migrate_resolved_paths.py [--verify-only] [--batch-size N]
"""

import os
import sys
import argparse
import datetime
import platform

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from modules import db
from modules.utils import convert_path_to_local


def _table_exists(cursor, table_name):
    """Check if a table exists in Firebird database."""
    cursor.execute(
        "SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ? AND RDB$SYSTEM_FLAG = 0",
        (table_name.upper(),)
    )
    return cursor.fetchone() is not None


def _index_exists(cursor, index_name):
    """Check if an index exists in Firebird database."""
    cursor.execute(
        "SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = ?",
        (index_name.upper(),)
    )
    return cursor.fetchone() is not None


def _view_exists(cursor, view_name):
    """Check if a view exists in Firebird database."""
    cursor.execute(
        "SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ? AND RDB$VIEW_BLR IS NOT NULL",
        (view_name.upper(),)
    )
    return cursor.fetchone() is not None


def create_table():
    """Create the resolved_paths table and indexes (Firebird-compatible)."""
    conn = db.get_db()
    c = conn.cursor()
    
    # Create resolved_paths table if not exists
    if not _table_exists(c, 'RESOLVED_PATHS'):
        c.execute('''CREATE TABLE resolved_paths (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            image_id INTEGER NOT NULL,
            windows_path VARCHAR(4000) NOT NULL,
            is_verified INTEGER DEFAULT 0,
            verification_date TIMESTAMP,
            last_checked TIMESTAMP
        )''')
    
    # Create indexes if not exist
    if not _index_exists(c, 'IDX_RESOLVED_PATHS_IMAGE'):
        c.execute("CREATE INDEX idx_resolved_paths_image ON resolved_paths(image_id)")
    # Note: Skipping index on windows_path as VARCHAR(4000) exceeds Firebird key size limit
    
    # Create view if not exists
    if not _view_exists(c, 'IMAGES_WITH_RESOLVED_PATHS'):
        c.execute('''CREATE VIEW images_with_resolved_paths AS
            SELECT 
                i.*,
                rp.windows_path as resolved_path,
                rp.is_verified,
                rp.verification_date
            FROM images i
            LEFT JOIN resolved_paths rp ON i.id = rp.image_id AND rp.is_verified = 1
        ''')
    
    conn.commit()
    conn.close()
    print("✓ Created resolved_paths table and indexes")


def convert_to_windows_path(path):
    """
    Convert any path format to Windows format.
    Handles WSL paths (/mnt/d/...) -> (D:\...).
    """
    if not path:
        return None
    
    # Already Windows format?
    if len(path) >= 2 and path[1] == ':':
        # Normalize slashes
        return path.replace('/', '\\')
    
    # WSL format?
    path_normalized = path.replace('\\', '/')
    if path_normalized.startswith('/mnt/'):
        parts = path_normalized.split('/')
        if len(parts) > 2 and len(parts[2]) == 1:
            drive = parts[2].upper()
            rest = '\\'.join(parts[3:])
            return f"{drive}:\\{rest}"
    
    # Unknown format, return as-is with backslashes
    return path.replace('/', '\\')


def backfill_resolved_paths(batch_size=100, verify_files=True):
    """
    Backfill resolved_paths for all existing images.
    
    Args:
        batch_size: Number of images to process before committing
        verify_files: Whether to verify file existence on disk
    
    Returns:
        Dict with statistics: {total, resolved, verified, failed}
    """
    conn = db.get_db()
    c = conn.cursor()
    
    # Get all images that don't have a resolved path yet
    c.execute('''
        SELECT i.id, i.file_path 
        FROM images i
        LEFT JOIN resolved_paths rp ON i.id = rp.image_id
        WHERE rp.id IS NULL AND i.file_path IS NOT NULL
    ''')
    images = c.fetchall()
    conn.close()
    
    stats = {
        'total': len(images),
        'resolved': 0,
        'verified': 0,
        'failed': 0
    }
    
    if not images:
        print("No images need backfilling.")
        return stats
    
    print(f"Processing {len(images)} images...")
    
    batch = []
    now = datetime.datetime.now()
    
    for i, row in enumerate(images):
        image_id = row[0]
        file_path = row[1]
        
        # Convert to Windows path
        windows_path = convert_to_windows_path(file_path)
        
        if not windows_path:
            stats['failed'] += 1
            continue
        
        # Verify file exists (if on Windows)
        is_verified = 0
        if verify_files and platform.system() == 'Windows':
            if os.path.exists(windows_path):
                is_verified = 1
                stats['verified'] += 1
        
        batch.append((image_id, windows_path, is_verified, now if is_verified else None, now))
        stats['resolved'] += 1
        
        # Commit batch
        if len(batch) >= batch_size:
            _insert_batch(batch)
            batch = []
            print(f"  Processed {i + 1}/{len(images)}...")
    
    # Final batch
    if batch:
        _insert_batch(batch)
    
    print(f"✓ Backfill complete")
    return stats


def _insert_batch(batch):
    """Insert a batch of resolved paths (Firebird-compatible)."""
    conn = db.get_db()
    c = conn.cursor()
    # Firebird: Use UPDATE OR INSERT MATCHING instead of SQLite's INSERT OR REPLACE
    c.executemany('''
        UPDATE OR INSERT INTO resolved_paths 
        (image_id, windows_path, is_verified, verification_date, last_checked)
        VALUES (?, ?, ?, ?, ?)
        MATCHING (image_id, windows_path)
    ''', batch)
    conn.commit()
    conn.close()


def verify_all_paths():
    """
    Verify all resolved paths still exist on disk.
    Updates is_verified flag accordingly.
    
    Returns:
        Dict with stats: {total, verified, not_found}
    """
    if platform.system() != 'Windows':
        print("Verification only works on Windows.")
        return {'total': 0, 'verified': 0, 'not_found': 0}
    
    conn = db.get_db()
    c = conn.cursor()
    c.execute("SELECT id, windows_path, is_verified FROM resolved_paths")
    rows = c.fetchall()
    conn.close()
    
    stats = {'total': len(rows), 'verified': 0, 'not_found': 0}
    
    now = datetime.datetime.now()
    verified_ids = []
    unverified_ids = []
    
    for row in rows:
        rp_id = row[0]
        windows_path = row[1]
        
        if os.path.exists(windows_path):
            verified_ids.append((1, now, now, rp_id))
            stats['verified'] += 1
        else:
            unverified_ids.append((0, None, now, rp_id))
            stats['not_found'] += 1
    
    # Batch update
    conn = db.get_db()
    c = conn.cursor()
    
    if verified_ids:
        c.executemany(
            "UPDATE resolved_paths SET is_verified = ?, verification_date = ?, last_checked = ? WHERE id = ?",
            verified_ids
        )
    
    if unverified_ids:
        c.executemany(
            "UPDATE resolved_paths SET is_verified = ?, verification_date = ?, last_checked = ? WHERE id = ?",
            unverified_ids
        )
    
    conn.commit()
    conn.close()
    
    return stats


def main():
    parser = argparse.ArgumentParser(description='Migrate resolved_paths table')
    parser.add_argument('--verify-only', action='store_true', 
                        help='Only verify existing paths, do not backfill')
    parser.add_argument('--batch-size', type=int, default=100,
                        help='Batch size for processing (default: 100)')
    parser.add_argument('--no-verify', action='store_true',
                        help='Skip file existence verification during backfill')
    args = parser.parse_args()
    
    print("=" * 60)
    print("Resolved Paths Migration")
    print("=" * 60)
    
    # Always ensure table exists
    create_table()
    
    if args.verify_only:
        print("\nVerifying existing paths...")
        stats = verify_all_paths()
        print(f"\nVerification Results:")
        print(f"  Total:     {stats['total']}")
        print(f"  Verified:  {stats['verified']}")
        print(f"  Not Found: {stats['not_found']}")
    else:
        print("\nBackfilling resolved paths...")
        stats = backfill_resolved_paths(
            batch_size=args.batch_size,
            verify_files=not args.no_verify
        )
        print(f"\nBackfill Results:")
        print(f"  Total Images: {stats['total']}")
        print(f"  Resolved:     {stats['resolved']}")
        print(f"  Verified:     {stats['verified']}")
        print(f"  Failed:       {stats['failed']}")
    
    print("\n" + "=" * 60)
    print("Migration complete!")
    print("=" * 60)


if __name__ == '__main__':
    main()
