import sqlite3
import os
import sys
import datetime
import time

# Configure Firebird Client Library Path
# Ensure fbclient.dll can be found
fb_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Firebird")
if os.path.exists(fb_path):
    os.environ["PATH"] += ";" + fb_path
    os.environ["FIREBIRD"] = fb_path # Essential for locating plugins/conf
    # specific for firebird-driver logic if needed, but PATH usually suffices for ctypes load
    # If not, we might need:
    # from firebird.driver import driver_config
    # driver_config.server_defaults.host.client_library.value = os.path.join(fb_path, "fbclient.dll")

# Try importing firebird driver
try:
    from firebird.driver import connect, driver_config
except ImportError:
    print("Error: firebird-driver not installed. Please run: pip install firebird-driver")
    sys.exit(1)

# Configure driver explicitly just in case


DB_FILE = "scoring_history.db"
FIREBIRD_DB = "scoring_history.fdb"
FB_CLIENT_DLL = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Firebird", "fbclient.dll")

def get_sqlite_conn():
    return sqlite3.connect(DB_FILE)

def get_firebird_conn(create_new=False):
    # For embedded, we point to the DB file. 
    # Ensure fbclient.dll is loaded from the Embedded folder
    
    # Configure driver to use our embedded DLL
    # We might need to register the server/client in firebird-driver config first?
    # For simplicity, we assume standard connection string if DLL is in path or configured.
    # But strictly for embedded:
    
    # dsn = f"localhost:{os.path.abspath(FIREBIRD_DB)}"
    # For Embedded/Local, use just the absolute path
    db_path = os.path.abspath(FIREBIRD_DB)
    
    print(f"DEBUG: DB Path = {db_path}")
    
    # Let's try basic connection. If it fails, we might need the user to set PATH to include Firebird folder.
    user = os.environ.get("ISC_USER", "sysdba")
    password = os.environ.get("ISC_PASSWORD", "masterkey")
    try:
        if create_new:
             # Create new DB
             print("Creating Firebird DB...")
             # page_size is not a valid kwarg for create_database in recent driver versions
             # It defaults to 8192 or 16384 usually.
             from firebird.driver import create_database
             # Pass db_path as positional argument 'dsn' to avoid internal UnboundLocalError in driver
             create_database(db_path, user=user, password=password)
             
             con = connect(database=db_path, user=user, password=password)
             return con
    except Exception as e:
        print(f"Error creating Firebird database: {e}")
        import traceback
        traceback.print_exc()
        # If creation fails, try to connect anyway, maybe it already exists
        pass # Fall through to regular connect

    return connect(database=db_path, user=user, password=password)


def migrate_schema(sqlite_conn, fb_conn):
    print("Migrating Schema...")
    # Map SQLite types to Firebird
    
    # TABLES
    tables = [
        """CREATE TABLE jobs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            input_path VARCHAR(4000),
            status VARCHAR(50),
            created_at TIMESTAMP,
            completed_at TIMESTAMP,
            log BLOB SUB_TYPE TEXT
        )""",
        
        """CREATE TABLE images (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id INTEGER,
            file_path VARCHAR(4000),
            file_name VARCHAR(255),
            file_type VARCHAR(20),
            score DOUBLE PRECISION,
            score_general DOUBLE PRECISION,
            score_technical DOUBLE PRECISION,
            score_aesthetic DOUBLE PRECISION,
            score_spaq DOUBLE PRECISION,
            score_ava DOUBLE PRECISION,
            score_koniq DOUBLE PRECISION,
            score_paq2piq DOUBLE PRECISION,
            score_liqe DOUBLE PRECISION,
            keywords BLOB SUB_TYPE TEXT,
            title VARCHAR(500),
            description BLOB SUB_TYPE TEXT,
            metadata BLOB SUB_TYPE TEXT,
            thumbnail_path VARCHAR(4000),
            scores_json BLOB SUB_TYPE TEXT,
            model_version VARCHAR(50),
            rating INTEGER,
            label VARCHAR(50),
            image_hash VARCHAR(64),
            folder_id INTEGER,
            stack_id INTEGER,
            created_at TIMESTAMP
        )""",
        
        """CREATE TABLE folders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            path VARCHAR(4000),
            parent_id INTEGER,
            is_fully_scored INTEGER DEFAULT 0,
            created_at TIMESTAMP
        )""",
        
        """CREATE TABLE stacks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255),
            best_image_id INTEGER,
            created_at TIMESTAMP
        )""",
        
        """CREATE TABLE file_paths (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            image_id INTEGER,
            path VARCHAR(4000),
            last_seen TIMESTAMP
        )""",
        
        """CREATE TABLE resolved_paths (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            image_id INTEGER NOT NULL,
            windows_path VARCHAR(4000) NOT NULL,
            is_verified INTEGER DEFAULT 0,
            verification_date TIMESTAMP,
            last_checked TIMESTAMP
        )"""
    ]
    
    cur = fb_conn.cursor()
    for ddl in tables:
        try:
            # Drop if exists (manual primitive way)
            table_name = ddl.split()[2]
            try:
                cur.execute(f"DROP TABLE {table_name}")
                fb_conn.commit()
            except:
                pass
            
            cur.execute(ddl)
            fb_conn.commit()
            print(f"Created table {table_name}")
        except Exception as e:
            print(f"Error creating table {ddl.split()[2]}: {e}")

    # Indices
    indices = [
        # "CREATE UNIQUE INDEX idx_images_file_path ON images(file_path)", # Too long for default page size
        "CREATE INDEX idx_images_folder_id ON images(folder_id)",
        "CREATE INDEX idx_images_stack_id ON images(stack_id)",
        "CREATE INDEX idx_image_hash ON images(image_hash)",
        # "CREATE UNIQUE INDEX idx_folders_path ON folders(path)", # Too long
        "CREATE INDEX idx_stack_score_general ON images(stack_id, score_general)",
        # "CREATE UNIQUE INDEX idx_file_paths_unique ON file_paths(image_id, path)" # Too long
    ]
    
    for idx in indices:
        try:
            cur.execute(idx)
            fb_conn.commit()
        except Exception as e:
            print(f"Index error: {e}")

    cur.close()


def migrate_data(sqlite_conn, fb_conn):
    print("Migrating Data...")
    
    tables_map = {
        "jobs": ["id", "input_path", "status", "created_at", "completed_at", "log"],
        "folders": ["id", "path", "parent_id", "is_fully_scored", "created_at"],
        "stacks": ["id", "name", "best_image_id", "created_at"],
        "images": ["id", "job_id", "file_path", "file_name", "file_type", "score", 
                  "score_general", "score_technical", "score_aesthetic", 
                  "score_spaq", "score_ava", "score_koniq", "score_paq2piq", "score_liqe",
                  "keywords", "title", "description", "metadata", "thumbnail_path", "scores_json",
                  "model_version", "rating", "label", "image_hash", "folder_id", "stack_id", "created_at"],
        "file_paths": ["id", "image_id", "path", "last_seen"],
        "resolved_paths": ["id", "image_id", "windows_path", "is_verified", "verification_date", "last_checked"]
    }
    
    sqlite_cur = sqlite_conn.cursor()
    fb_cur = fb_conn.cursor()
    
    for table, columns in tables_map.items():
        print(f"Migrating {table}...")
        try:
            # Select all from sqlite
            col_str = ", ".join(columns)
            sqlite_cur.execute(f"SELECT {col_str} FROM {table}")
            rows = sqlite_cur.fetchall()
            
            if not rows:
                continue
                
            # Insert into firebird
            placeholders = ", ".join(["?" for _ in columns])
            insert_sql = f"INSERT INTO {table} ({col_str}) VALUES ({placeholders})"
            
            # Pre-process rows for DateTime conversion
            processed_rows = []
            
            # Identify timestamp columns indices
            ts_indices = []
            for i, col in enumerate(columns):
                if "created_at" in col or "completed_at" in col or "last_seen" in col or "verification" in col or "checked" in col:
                    ts_indices.append(i)
            
            for row in rows:
                new_row = list(row)
                for idx in ts_indices:
                    val = new_row[idx]
                    if val and isinstance(val, str):
                        try:
                            # Parse ISO format (SQLite default)
                            # Handle potential fractional seconds weirdness if any
                            new_row[idx] = datetime.datetime.fromisoformat(val)
                        except ValueError:
                             pass
                processed_rows.append(tuple(new_row))

            fb_cur.executemany(insert_sql, processed_rows)
            fb_conn.commit()
            print(f"Migrated {len(rows)} rows for {table}")
            
        except Exception as e:
            print(f"Error migrating {table}: {e}")
            
    fb_cur.close()

def main():
    if not os.path.exists(DB_FILE):
        print(f"Source DB {DB_FILE} not found!")
        return

    # User must have Firebird installed/unzipped
    # For now, we assume they have.
    
    print("Connecting to SQLite...")
    s_conn = get_sqlite_conn()
    
    print("Creating Firebird DB...")
    f_conn = get_firebird_conn(create_new=False)
    
    try:
        migrate_schema(s_conn, f_conn)
        migrate_data(s_conn, f_conn)
        print("Migration Complete successfully!")
    except Exception as e:
        print(f"Migration Failed: {e}")
        import traceback
        traceback.print_exc()
    finally:
        s_conn.close()
        f_conn.close()

if __name__ == "__main__":
    main()
